name: MacRDP

on:
  workflow_dispatch:

jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and start remote access
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/start.sh"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"

      - name: Setup login script
        run: |
          curl -s -o login.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/login.sh"
          chmod +x login.sh
          bash login.sh

      - name: Keep runner alive (no tmate)
        run: |
          echo "Runner is active. Keeping session alive..."
          sleep 21600
